a.out:  compile
	g++ -o a.out_client *.o
	rm -f *.o

compile:	../src/client/*.cpp ../src/client/include/*.h ../src/client/src/*.cpp
	g++ -c ../src/client/*.cpp ../src/client/src/*.cpp
run:
	./a.out_client
